[package]
name = "addalias"
version = "1.3.2"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.22"
termion="1.5.6"

[[bin]]
name = "addalias"
path = "src/main.rs"
